version: '3.8'

services:
  backend:
    build: ./backend 
    ports:
      - "3001:3001" 
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      PORT: 3001 

  frontend:
    build: ./frontend 
    ports:
      - "3000:80" 
    environment:
      REACT_APP_BACKEND_HOST: backend 
      REACT_APP_BACKEND_PORT: 3001 
    depends_on:
      - backend 